version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: dashboard-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dashboard
      MYSQL_USER: taphuc
      MYSQL_PASSWORD: 123456
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    container_name: dashboard-adminer
    restart: always
    ports:
      - "9999:8080"
    depends_on:
      - db

volumes:
  db-data:
